### ISSUE TITLE
Gurkirat | Lab 5 Activity | Step 7: Bug Report | End-to-end 

### ISSUE THREAD

**Issue by gurkiratb03** [TC6IDM/Flexx#12]
Bug Report: Progress bar linked to completed tasks

Title: Progress bar does not update immediately after marking a task as completed
Description: When marking a task as completed, the progress bar does not update immediately to reflect the change. The progress bar only updates after refreshing the page or navigating to another section and returning to the "Progress Tracker" page.
Steps to Reproduce:
Launch the application
Navigate to the "Progress Tracker" page
Add a new task
Mark the task as completed
Expected Result:
The progress bar should update immediately after marking a task as completed, showing the accurate percentage of completed tasks.
Actual Result: The progress bar does not update immediately. The user has to refresh the page or navigate to another section and return to the "Progress Tracker" page to see the updated progress bar.
Environment:
Browser: Google Chrome Version 98.0.4758.102
Operating System: Windows 11 Home
Priority: Medium
Severity: Minor

Bug Report: Database entry for goals

Title: Unable to save a goal containing a single quote (') character
Description:
When trying to save a goal that contains a single quote (') character, the application does not save the goal and displays an error message.
Steps to Reproduce:
Launch the application
Navigate to the "Progress Tracker" page
Add a new goal containing a single quote character, e.g., "Get a Bachelor's degree"
Click "Save" button

Expected Result: The goal should be saved to the database, and the message "Data has been saved to the database." should be displayed.
Actual Result: The goal is not saved, and an error message is displayed: "Error occurred while saving data."
Environment:
Browser: Mozilla Firefox Version 97.0
Operating System: macOS Monterey 12.1
Priority: Medium
Severity: Minor

**Comment by elysedhaliwal** [comment]
Changes been made, progress bar now works with accurate percentage
