### ISSUE TITLE
Elyse | Lab 5 activity | Step 7: Bug Report | End-to-End

### ISSUE THREAD

**Issue by elysedhaliwal** [TC6IDM/Flexx#16]
Bug: "Workout Types" combo box remains disabled after selecting a valid muscle group

Description:The "Workout Types" combo box remains disabled and does not enable itself when a valid muscle group is selected from the "Muscle Group" combo box. This issue prevents users from choosing a workout type and obtaining the corresponding results.

Steps:
1. Launch the application.
2. Select a muscle group (e.g., "Arms") from the "Muscle Group" combo box.

Expected Result:
The "Workout Types" combo box should be enabled and display the corresponding workout types for the selected muscle group.

Actual Result:
The "Workout Types" combo box remains disabled and does not display the corresponding workout types for the selected muscle group. After multiple uses on combo box

Severity: Medium

**Comment by gurkiratb03** [comment]
The issue has been resolved and the "Workout Types" combo box now enables itself and displays the corresponding workout types for the selected muscle group. Marking the issue as closed.
